### ISSUE TITLE
Add 'openshift_hosted_registry_replicas=3'

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/openshift-cic#2]
Add this option for every scenario that includes Registry. This output does not require a corresponding question. The default of 3 registry pods is a best practice. They all use the SAME glusterfs PV. 

Added below as example
# registry
openshift_hosted_registry_storage_kind=glusterfs
openshift_hosted_registry_storage_volume_size=10
openshift_hosted_registry_replicas=3
openshift_hosted_registry_selector={"region":"infra"}

**Comment by ramkrsna** [comment]
https://github.com/red-hat-storage/openshift-cic/pull/10

**Comment by netzzer** [comment]
#10 merged
