### ISSUE TITLE
Add totalcalc to validate total storage available after storage claims

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/openshift-cic#4]
WIP calcs
cluster_storage = len(raw_devices) * raw_storage_size * len(app_hosts)
                block_calc = registry_pvsize + block_host_size
                totalcalc = block_calc
                if totalcalc < cluster_storage :
                        print "cluster_storage=%d" % cluster_storage
                        print "totalstoragecalc=%d" % totalcalc
                        print "\033[91m Total Storage is Oversubscribed \033[0m"
                        print "\033[91m Please provision the storage \033[0m"
                        print "Total storage calc = block_host_vol_size (if it exists) \n"
                        print "+registry PV < sum of storage devices per node \033[0m"
                        exit()

**Comment by netzzer** [comment]
After thinking about this there are 3 items needed.
- Report on total usable storage per cluster 
- Report on total storage allocation based on size of block_host_vol_size + size of registry PV per cluster (in the case of two cluster the 'app' cluster has zero storage allocation)
- Verify that the no PV size choices are LARGER than the raw storage device (i.e. registry PV = 200GB and raw storage device size = 100GB) per cluster (in the case of two cluster this would not apply to the 'app' cluster)

**Example one cluster** 
Enter your choice [1-5] : 4
------------------------------------------------------------
For this configuration 7 nodes are recommended
With a minimum of 3 required 
------------------------------------------------------------
How many nodes are available ?:  3
What hosts will be used for application storage (IP/FQDN) ?: aaa.com bbb.com ccc.com
What are the raw storage devices for these hosts(/dev/<device>) ?: /dev/sdb /dev/sdc
What is the size of each raw storage device (GB) ?: 100
What is the size for the registry persistent volume (GB)?: 20
How many replicas for logging ?: 3
What is the size for each logging persistent volume (GB) ?: 20
What is the size for each metrics persistent volume (GB) ?: 20
------------------------------------------------------------
Cluster 1
Total Storage allocated (GB) = 104
Total Storage available (GB) = 200 
------------------------------------------------------------
**Example two cluster**
Enter your choice [1-5] : 4
------------------------------------------------------------
For this configuration 7 nodes are recommended
With a minimum of 3 required 
------------------------------------------------------------
How many nodes are available ?:  6
What hosts will be used for application storage (IP/FQDN) ?: aaa.com bbb.com ccc.com
What are the raw storage devices for these hosts(/dev/<device>) ?: /dev/sdb
What is the size of each raw storage device (GB) ?: 100
What is the size for the registry persistent volume (GB)?: 150
How many replicas for logging ?: 3
What is the size for each logging persistent volume (GB) ?: 25
What is the size for each metrics persistent volume (GB) ?: 25
What hosts will be used for CNS logging + metrics backend storage  (IP/FQDN) ?:  ddd.com eee.com fff.com
What are the raw storage devices for logging + metrics backend on these hosts (/dev/<device>) ?: /dev/sdb /dev/sdc /dev/sdd
What is the size of each raw storage device (GB) ? : 100
------------------------------------------------------------
Cluster 1
Total Storage allocated (GB) = 0
Total Storage available (GB) = 100 
Cluster2
Total Storage allocated (GB) = 280 
Total Storage available (GB) = 300
>>>Warning one or more persistent volumes are larger than the raw storage device size<<<
------------------------------------------------------------

**Comment by ramkrsna** [comment]
The PR #22 handles this issue. Needs testing.
