### ISSUE TITLE
Exits with error, "Enter a valid supported version of OCP" when entered 3.10 as version

### ISSUE THREAD

**Issue by ashmitha7** [red-hat-storage/openshift-cic#44]
The tool exits with an error saying that the version entered is not supported when entering 3.10 as the answer. I think it needs some change in how it's accepting the answers.

$ ./cic.py
What version of OpenShift Container Platform are you deploying (3.9 or 3.10)?: 3.10 
Enter a valid supported version of OCP

It worked the next time I tried to execute.

**Comment by ramkrsna** [comment]
@ashmitha7  Thank you for reporting the issue. Do let me know if this behavior is persistent.

**Comment by ashmitha7** [comment]
@ramkrsna  yes sure.

**Comment by netzzer** [comment]
To fix this issue need to remove the 'trailing whitespace' from all CIC user inputs.

**Comment by netzzer** [comment]
Resolved by PR #48
