### ISSUE TITLE
ocs.py refers to 3.9 (wasn't it supposed to be fore 3.10?)

### ISSUE THREAD

**Issue by mykaul** [red-hat-storage/openshift-cic#46]
For example:
https://github.com/red-hat-storage/openshift-cic/blob/master/ocs.py#L11

**Comment by ramkrsna** [comment]
@mykaul Yes, it is. At the moment the 3.10 images are not available. We already have that in consideration in this issue https://github.com/red-hat-storage/openshift-cic/issues/41 . We will change it to 3.10 once the images are available on GA. right now it would fail. Hence we have referred to 3.9

**Comment by mykaul** [comment]
@ramkrsna - that doesn't explain why the 3.10 related code relates to 3.9.

**Comment by netzzer** [comment]
To fix this issue please remove sentence below from ocs.py and cns.py comment area given it is no longer true. These combos are now supported by CIC: OCP 3.9+CNS 3.9, OCP 3.10+CNS 3.9, OCP 3.10 + OCS 3.10 (after OCS 3.10 GA). 
```
This tool is very highly version dependent. It is currently configured to work with OpenShift 3.9 and CNS 3.9.
```
Example for ocs.ppy - https://github.com/red-hat-storage/openshift-cic/blob/master/ocs.py#L11

**Comment by netzzer** [comment]
File no longer exists now that CIC uses templates.
