### ISSUE TITLE
OCP 3.9 chosen should recommend CNS 3.9 or 3.10?

### ISSUE THREAD

**Issue by jaywryan** [red-hat-storage/openshift-cic#53]
When specifying OCP 3.9 the results output gluster images for CNS 3.10.  Is there guidance/support for OCP 3.9 with CNS(OCS) 3.10?  I've seen the inverse but I wasn't sure if this was a supportable configuration or a bug in the openshift-cic tool.  @netzzer

**Comment by ramkrsna** [comment]
@jaywryan The container images would be the latest available.

**Comment by netzzer** [comment]
Currently support is 1+/1- compared to version of OCP. That said, if OCP 3.9 is deployed always specify v3.10 given the many glusterblock fixes in OCS 3.10. Soon there should to support for +2 which means OCP 3.9 can be used with OCS 3.11 which has even more glusterblock fixes.
