### ISSUE TITLE
Traceback failure for choice [3] and 7 nodes

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/openshift-cic#6]
CNS metrics backend storage = 4 nodes fails. Inputting 3 nodes works correctly. 

Enter your choice [1-5] : 3
------------------------------------------------------------
For this configuration 7 nodes are recommended
With a minimum of 3 required 
------------------------------------------------------------
How many nodes are available ?:  7
What hosts will be used for application storage (IP/FQDN) ?: aaa.com bbb.com ccc.com
What are the raw storage devices for these hosts(/dev/<device>) ?: /dev/sdb
What is the size of each raw storage device (GB) ?: 100
What is the size for the registry persistent volume (GB)?: 10
What is the size for each metrics persistent volume (GB) ?: 20
What hosts will be used for CNS metrics backend storage  (IP/FQDN) ?:  ddd.com eee.com fff.com ggg.com
What are the raw storage devices for metrics backend on these hosts (/dev/<device>) ?: /dev/sdb
What is the size of each raw storage device (GB) ? : 100
....omitted....
[glusterfs]
aaa.com glusterfs_devices='["/dev/sdb"]'
bbb.com glusterfs_devices='["/dev/sdb"]'
ccc.com glusterfs_devices='["/dev/sdb"]'
Traceback (most recent call last):
  File "./cic.py", line 490, in <module>
    print  app_hosts[3] + " glusterfs_devices=" + "'" + json.dumps(raw_devices) + "'"
IndexError: list index out of range

**Comment by ramkrsna** [comment]
We would require to find better allocation/computation for the question, How many nodes are available ?: X
X, could be anywhere from the minimum of  3 or 4 -> the highest theoretical limit  of kubernetes nodes or gluster nodes (4096 ) based of which the distribution of  nodes used for applications vs nodes used for logging/metrics can be computed.
