### ISSUE TITLE
Add 'glusterfs_zone=[1-3]' to [glusterfs] and [glusterfs_registry] definition

### ISSUE THREAD

**Issue by netzzer** [red-hat-storage/openshift-cic#7]
Heketi needs this for node/brick volume placement, example:
[glusterfs]
node01.example.com glusterfs_ip=10.0.0.1 glusterfs_zone=1 glusterfs_devices='[ "/dev/xvdd" ]'
node02.example.com glusterfs_ip=10.0.0.2 glusterfs_zone=2 glusterfs_devices='[ "/dev/xvdd" ]'
node03.example.com glusterfs_ip=10.0.0.3 glusterfs_zone=3 glusterfs_devices='[ "/dev/xvdd" ]'

For the 4 node app cluster the zone count should start over, i.e. 4th node, glusterfs_zone=1.

**Comment by ramkrsna** [comment]
This issue has been fixed by #9
